import mongoose from "mongoose";
import AgentActionPlan, { type IAgentActionPlan, type IActionStep } from "../models/AgentActionPlan";
import HiveMindRecommendation from "../models/HiveMindRecommendation";
import { getProjectContext } from "./unifiedContext";
import { detectCycles, type StructuredRisk, type KnowledgeGap } from "./hiveMindService";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Minimal shape of a lean graph node returned by getProjectContext() */
interface WorkspaceNode {
  id: string;
  title: string;
  category: string;
  description?: string;
  data?: { status?: string; owner?: string; assignee?: string; priority?: string };
}

/** Minimal shape of a lean graph edge returned by getProjectContext() */
interface WorkspaceEdge {
  id: string;
  source: string;
  target: string;
}

/** Minimal shape of a lean active document returned by getProjectContext() */
interface WorkspaceDoc {
  id: string;
  nodeId?: string;
}

/** Mongoose recommendation lean object used in plan generation */
interface RecommendationLean {
  _id: mongoose.Types.ObjectId;
  title: string;
  reason: string;
  type: string;
  confidence: number;
  status: string;
  suggestedActions: string[];
  relatedEntities: Array<{ entityId: string; entityType: string; title: string }>;
}

export interface ActionSimulationResult {
  planId: string;
  // Graph deltas
  nodesAdded: number;
  nodesModified: number;
  nodesDeleted: number;
  // Diagnostic deltas
  risksResolved: number;
  risksCreated: number;
  gapsResolved: number;
  gapsCreated: number;
  ownershipChanges: number;
  dependencyChanges: number;
  // Health & momentum estimates
  estimatedHealthImpact: number;   // delta from current health
  estimatedMomentumImpact: number; // delta from current momentum
  // Affected entity summary
  affectedEntityCount: number;
  affectedEntities: Array<{ entityId: string; entityType: string; title: string; changeType: string }>;
  // Risk analysis
  reversibleSteps: number;
  irreversibleSteps: number;
  overallRiskLevel: "low" | "medium" | "high" | "critical";
}

export interface GeneratePlansOptions {
  confidenceThreshold?: number; // default 0.6
  maxPlansPerRun?: number;       // default 20
  expiryHours?: number;          // default 72
}

// ---------------------------------------------------------------------------
// Quality Score Calculator
// ---------------------------------------------------------------------------

/**
 * Computes actionQualityScore (0–100) based on:
 * - confidence (40%)
 * - reversibility of steps (30%)
 * - entity count — fewer affected = more surgical = better (15%)
 * - historical effectiveness proxied by recommendation confidence (15%)
 */
function computeActionQualityScore(
  confidence: number,
  steps: IActionStep[],
  affectedEntityCount: number
): number {
  const confidenceScore = confidence * 100 * 0.4;

  const totalSteps = steps.length;
  const reversibleSteps = steps.filter((s) => s.reversibility === "reversible").length;
  const reversibilityScore =
    totalSteps > 0 ? (reversibleSteps / totalSteps) * 100 * 0.3 : 60 * 0.3;

  // Prefer plans affecting 1–5 entities (surgical), penalize > 10
  const entityScore =
    affectedEntityCount <= 1
      ? 100
      : affectedEntityCount <= 5
      ? 85
      : affectedEntityCount <= 10
      ? 60
      : 35;
  const entityContrib = entityScore * 0.15;

  // Historical effectiveness proxy: use confidence as a stand-in
  const historicalScore = confidence * 100 * 0.15;

  const raw = confidenceScore + reversibilityScore + entityContrib + historicalScore;
  return Math.min(100, Math.max(0, Math.round(raw)));
}

// ---------------------------------------------------------------------------
// Risk Score Calculator
// ---------------------------------------------------------------------------

function computeRiskScore(riskLevel: "low" | "medium" | "high" | "critical"): number {
  const map: Record<string, number> = {
    low: 20,
    medium: 45,
    high: 70,
    critical: 95,
  };
  return map[riskLevel] ?? 50;
}

// ---------------------------------------------------------------------------
// Plan Builder Helpers
// ---------------------------------------------------------------------------

function makeExpiresAt(hours: number): Date {
  const d = new Date();
  d.setHours(d.getHours() + hours);
  return d;
}

function buildAuditLog(actorName: string): IAgentActionPlan["structuredAuditLogs"][0] {
  return {
    actorId: undefined,
    actorName,
    action: "submit",
    notes: "Plan auto-generated by HiveMind Action Engine.",
    timestamp: new Date(),
  };
}

// ---------------------------------------------------------------------------
// Plan Templates
// ---------------------------------------------------------------------------

function planFromGapFeatureNoPrd(
  gap: KnowledgeGap,
  expiryHours: number
): Partial<IAgentActionPlan> {
  const entity = gap.relatedEntities[0];
  if (!entity) return {};

  const steps: IActionStep[] = [
    {
      stepNumber: 1,
      actionType: "create_document",
      params: {
        title: `PRD: ${entity.title}`,
        type: "prd",
        linkedNodeId: entity.entityId,
        templateHint: "prd_template",
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Creates a structured PRD document and links it to the feature node.",
    },
    {
      stepNumber: 2,
      actionType: "create_node",
      params: {
        category: "Task",
        title: `Implementation Tasks: ${entity.title}`,
        status: "Todo",
        linkedFeatureId: entity.entityId,
        owner: null, // No auto-assignment — ownership must be proposed separately
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Creates a task node scaffold for implementation tracking.",
    },
  ];

  const affectedEntityCount = steps.reduce((acc, s) => acc + s.affectedEntities.length, 0);
  const riskLevel = "low";
  const confidence = 0.85;

  return {
    title: `Resolve Documentation Gap: ${entity.title}`,
    description: `Feature node "${entity.title}" exists without a PRD. This plan creates a document stub and a task node to resolve the gap.`,
    reason: `Gap detected: feature_no_prd. A feature without a spec creates unclear implementation expectations and reduces health score.`,
    confidence,
    riskLevel,
    riskScore: computeRiskScore(riskLevel),
    actionQualityScore: computeActionQualityScore(confidence, steps, affectedEntityCount),
    steps,
    sourceGapIds: [gap.id],
    sourceRiskIds: [],
    sourceRecommendationIds: [],
    sourceMissionIds: [],
    expiresAt: makeExpiresAt(expiryHours),
    structuredAuditLogs: [buildAuditLog("HiveMind Action Engine")],
  };
}

function planFromGapArchNoTech(
  gap: KnowledgeGap,
  expiryHours: number
): Partial<IAgentActionPlan> {
  const entity = gap.relatedEntities[0];
  if (!entity) return {};

  const steps: IActionStep[] = [
    {
      stepNumber: 1,
      actionType: "create_node",
      params: {
        category: "Tech Stack",
        title: `Tech Stack for ${entity.title}`,
        description: "Define the technology stack associated with this architecture component.",
        owner: null,
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Creates a Tech Stack node to represent implementation technology.",
    },
    {
      stepNumber: 2,
      actionType: "create_edge",
      params: {
        sourceId: entity.entityId,
        targetId: "__NEW_TECH_STACK_NODE__",
        relationType: "depends_on",
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Links the architecture node to its tech stack, closing the graph gap.",
    },
  ];

  const affectedEntityCount = 2;
  const riskLevel = "low";
  const confidence = 0.75;

  return {
    title: `Link Tech Stack to Architecture: ${entity.title}`,
    description: `Architecture component "${entity.title}" has no linked tech stack. This plan creates a tech node and connects it.`,
    reason: `Gap detected: arch_no_tech. Unlinking architecture from implementation technology reduces clarity of deployment dependencies.`,
    confidence,
    riskLevel,
    riskScore: computeRiskScore(riskLevel),
    actionQualityScore: computeActionQualityScore(confidence, steps, affectedEntityCount),
    steps,
    sourceGapIds: [gap.id],
    sourceRiskIds: [],
    sourceRecommendationIds: [],
    sourceMissionIds: [],
    expiresAt: makeExpiresAt(expiryHours),
    structuredAuditLogs: [buildAuditLog("HiveMind Action Engine")],
  };
}

function planFromRiskCycle(
  risk: StructuredRisk,
  expiryHours: number
): Partial<IAgentActionPlan> {
  const entities = risk.relatedEntities.slice(0, 4);

  const steps: IActionStep[] = [
    {
      stepNumber: 1,
      actionType: "delete_edge",
      params: {
        sourceId: entities[entities.length - 1]?.entityId ?? "",
        targetId: entities[0]?.entityId ?? "",
        reason: "Breaking circular dependency loop to restore acyclic graph structure.",
      },
      reversibility: "reversible",
      affectedEntities: entities,
      expectedImpact: "Removes the back-edge completing the cycle, resolving the architectural deadlock.",
    },
    {
      stepNumber: 2,
      actionType: "create_document",
      params: {
        title: `Architecture Decision Record: Cycle Resolution`,
        type: "adr",
        linkedNodeId: entities[0]?.entityId ?? "",
        templateHint: "adr_template",
      },
      reversibility: "reversible",
      affectedEntities: entities.slice(0, 1),
      expectedImpact: "Documents the architectural decision to break the cycle for future team reference.",
    },
  ];

  const affectedEntityCount = entities.length;
  const riskLevel = "critical";
  const confidence = 0.95;

  return {
    title: `Break Circular Dependency Loop`,
    description: `Circular dependency detected across ${entities.length} nodes. This plan removes the back-edge and documents the architectural decision.`,
    reason: `Risk detected: Circular dependency cycle. Graph deadlocks prevent clear critical path traversal and block topological ordering.`,
    confidence,
    riskLevel,
    riskScore: computeRiskScore(riskLevel),
    actionQualityScore: computeActionQualityScore(confidence, steps, affectedEntityCount),
    steps,
    sourceRiskIds: [risk.id],
    sourceGapIds: [],
    sourceRecommendationIds: [],
    sourceMissionIds: [],
    expiresAt: makeExpiresAt(expiryHours),
    structuredAuditLogs: [buildAuditLog("HiveMind Action Engine")],
  };
}

function planFromRiskBlocked(
  risk: StructuredRisk,
  expiryHours: number
): Partial<IAgentActionPlan> {
  const entity = risk.relatedEntities[0];
  if (!entity) return {};

  const steps: IActionStep[] = [
    {
      stepNumber: 1,
      actionType: "assign_owner",
      params: {
        nodeId: entity.entityId,
        owner: null, // Ownership must be explicitly assigned by a human
        reason: "Blocked node requires a designated owner to unblock.",
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Proposes ownership assignment to unblock the work item.",
    },
    {
      stepNumber: 2,
      actionType: "create_node",
      params: {
        category: "Task",
        title: `Unblock: ${entity.title}`,
        status: "In Progress",
        description: "Investigate and resolve the blocker for this work item.",
        owner: null,
        linkedFeatureId: entity.entityId,
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Creates an explicit unblock task to track resolution efforts.",
    },
  ];

  const affectedEntityCount = 2;
  const riskLevel = "high";
  const confidence = 0.9;

  return {
    title: `Unblock Work Item: ${entity.title}`,
    description: `Node "${entity.title}" is blocked. This plan proposes an owner assignment and creates an unblock task node.`,
    reason: `Risk detected: Blocked work item. Blocked nodes reduce sprint momentum and can cascade downstream.`,
    confidence,
    riskLevel,
    riskScore: computeRiskScore(riskLevel),
    actionQualityScore: computeActionQualityScore(confidence, steps, affectedEntityCount),
    steps,
    sourceRiskIds: [risk.id],
    sourceGapIds: [],
    sourceRecommendationIds: [],
    sourceMissionIds: [],
    expiresAt: makeExpiresAt(expiryHours),
    structuredAuditLogs: [buildAuditLog("HiveMind Action Engine")],
  };
}

function planFromUnassignedNode(
  node: { id: string; title: string; category: string },
  expiryHours: number
): Partial<IAgentActionPlan> {
  const entity = { entityId: node.id, entityType: "node", title: node.title };

  const steps: IActionStep[] = [
    {
      stepNumber: 1,
      actionType: "assign_owner",
      params: {
        nodeId: node.id,
        owner: null, // Never auto-assign — must be a human decision
        reason: `${node.category} node "${node.title}" has no owner.`,
      },
      reversibility: "reversible",
      affectedEntities: [entity],
      expectedImpact: "Proposes that a team member be manually designated as the owner of this node.",
    },
  ];

  const affectedEntityCount = 1;
  const riskLevel = "medium";
  const confidence = 0.8;

  return {
    title: `Assign Owner: ${node.title}`,
    description: `${node.category} node "${node.title}" has no designated owner. This plan proposes assigning ownership to ensure accountability.`,
    reason: `Unassigned work item detected. Nodes without owners create unclear responsibility and reduce team accountability.`,
    confidence,
    riskLevel,
    riskScore: computeRiskScore(riskLevel),
    actionQualityScore: computeActionQualityScore(confidence, steps, affectedEntityCount),
    steps,
    sourceRiskIds: [],
    sourceGapIds: [],
    sourceRecommendationIds: [],
    sourceMissionIds: [],
    expiresAt: makeExpiresAt(expiryHours),
    structuredAuditLogs: [buildAuditLog("HiveMind Action Engine")],
  };
}

function planFromRecommendation(
  rec: {
    _id: mongoose.Types.ObjectId;
    title: string;
    reason: string;
    type: string;
    confidence: number;
    relatedEntities: Array<{ entityId: string; entityType: string; title: string }>;
    suggestedActions: string[];
  },
  expiryHours: number
): Partial<IAgentActionPlan> {
  const entity = rec.relatedEntities[0];
  const steps: IActionStep[] = [];

  // Map suggestion actions to concrete steps
  if (rec.type === "document" && entity) {
    steps.push({
      stepNumber: 1,
      actionType: "create_document",
      params: {
        title: `Document: ${entity.title}`,
        type: "prd",
        linkedNodeId: entity.entityId,
      },
      reversibility: "reversible",
      affectedEntities: rec.relatedEntities.slice(0, 3),
      expectedImpact: rec.suggestedActions[0] || "Creates a documentation artifact.",
    });
  } else if (rec.type === "relationship" && entity) {
    steps.push({
      stepNumber: 1,
      actionType: "create_edge",
      params: {
        sourceId: entity.entityId,
        targetId: "__RECOMMENDED_TARGET__",
        relationType: "depends_on",
      },
      reversibility: "reversible",
      affectedEntities: rec.relatedEntities.slice(0, 3),
      expectedImpact: rec.suggestedActions[0] || "Creates a dependency relationship.",
    });
  } else if (rec.type === "owner" && entity) {
    steps.push({
      stepNumber: 1,
      actionType: "assign_owner",
      params: {
        nodeId: entity.entityId,
        owner: null, // Never auto-assign
        reason: rec.reason,
      },
      reversibility: "reversible",
      affectedEntities: rec.relatedEntities.slice(0, 2),
      expectedImpact: rec.suggestedActions[0] || "Assigns ownership to the node.",
    });
  } else if (rec.type === "architecture" && entity) {
    steps.push({
      stepNumber: 1,
      actionType: "create_node",
      params: {
        category: "Tech Stack",
        title: `Tech Stack for ${entity.title}`,
        owner: null,
      },
      reversibility: "reversible",
      affectedEntities: rec.relatedEntities.slice(0, 2),
      expectedImpact: rec.suggestedActions[0] || "Adds tech stack node for the architecture component.",
    });
    steps.push({
      stepNumber: 2,
      actionType: "create_edge",
      params: {
        sourceId: entity.entityId,
        targetId: "__NEW_TECH_STACK_NODE__",
        relationType: "depends_on",
      },
      reversibility: "reversible",
      affectedEntities: rec.relatedEntities.slice(0, 2),
      expectedImpact: "Links the architecture node to its implementation stack.",
    });
  } else if (entity) {
    // Generic fallback step
    steps.push({
      stepNumber: 1,
      actionType: "update_node",
      params: {
        nodeId: entity.entityId,
        updates: { status: "In Progress" },
      },
      reversibility: "reversible",
      affectedEntities: rec.relatedEntities.slice(0, 2),
      expectedImpact: rec.suggestedActions[0] || "Updates the node based on recommendation.",
    });
  }

  if (steps.length === 0) return {};

  const affectedEntityCount = steps.reduce((acc, s) => acc + s.affectedEntities.length, 0);
  const riskLevel: "low" | "medium" | "high" | "critical" =
    rec.type === "relationship" ? "medium" : "low";

  return {
    title: `Execute Recommendation: ${rec.title}`,
    description: `Action plan derived from HiveMind recommendation. Reason: ${rec.reason}`,
    reason: rec.reason,
    confidence: rec.confidence,
    riskLevel,
    riskScore: computeRiskScore(riskLevel),
    actionQualityScore: computeActionQualityScore(rec.confidence, steps, affectedEntityCount),
    steps,
    sourceRiskIds: [],
    sourceGapIds: [],
    sourceRecommendationIds: [rec._id],
    sourceMissionIds: [],
    expiresAt: makeExpiresAt(expiryHours),
    structuredAuditLogs: [buildAuditLog("HiveMind Action Engine")],
  };
}

// ---------------------------------------------------------------------------
// Main: generateActionPlans
// ---------------------------------------------------------------------------

/**
 * Runs full diagnostic analysis and generates multi-step action plans.
 * Plans are stored as PROPOSED and never auto-executed.
 * Deduplicates by checking for existing non-rejected/non-expired plans with same title.
 */
export async function generateActionPlans(
  hiveId: string,
  options: GeneratePlansOptions = {}
): Promise<{ generated: number; skipped: number; plans: IAgentActionPlan[] }> {
  const confidenceThreshold = options.confidenceThreshold ?? 0.6;
  const maxPlansPerRun = options.maxPlansPerRun ?? 20;
  const expiryHours = options.expiryHours ?? 72;

  // 1. Pull workspace diagnostics (re-runs lightweight rule engine)
  const context = await getProjectContext(hiveId);
  const nodes = context.nodes || [];
  const edges = context.edges || [];
  const activeDocs = context.activeDocuments || [];

  const nodeLookup = new Map<string, WorkspaceNode>(nodes.map((n: WorkspaceNode) => [n.id, n]));

  // 2. Re-compute rule-based diagnostics inline (no LLM)
  const cycles = detectCycles(nodes, edges);

  const blockedNodes = nodes.filter((n: WorkspaceNode) => n.data?.status === "Blocked");

  // Gaps
  const gaps: KnowledgeGap[] = [];
  const docFeatureNodeIds = new Set((activeDocs as WorkspaceDoc[]).map((d) => d.nodeId).filter(Boolean));
  const features = (nodes as WorkspaceNode[]).filter((n) => n.category === "Feature");
  features.forEach((feat) => {
    if (!docFeatureNodeIds.has(feat.id)) {
      gaps.push({
        id: `gap-prd-${feat.id}`,
        title: `Missing Spec: ${feat.title}`,
        type: "feature_no_prd",
        description: `Feature node "${feat.title}" has no PRD.`,
        relatedEntities: [{ entityId: feat.id, entityType: "node", title: feat.title }],
      });
    }
  });

  const archNodes = (nodes as WorkspaceNode[]).filter((n) => n.category === "Architecture");
  archNodes.forEach((arch) => {
    const hasTech = (edges as WorkspaceEdge[]).some((e) => {
      const otherId =
        e.source === arch.id ? e.target : e.target === arch.id ? e.source : null;
      if (otherId) {
        const other = nodeLookup.get(otherId);
        return other?.category === "Tech Stack";
      }
      return false;
    });
    if (!hasTech) {
      gaps.push({
        id: `gap-tech-${arch.id}`,
        title: `Unsupported Architecture: ${arch.title}`,
        type: "arch_no_tech",
        description: `Architecture node "${arch.title}" has no tech stack link.`,
        relatedEntities: [{ entityId: arch.id, entityType: "node", title: arch.title }],
      });
    }
  });

  // Risks
  const risks: StructuredRisk[] = [];
  const riskNodes = nodes.filter(
    (n) => n.category === "Risk" && n.data?.status !== "Done" && n.data?.status !== "Resolved"
  );
  riskNodes.forEach((r) => {
    risks.push({
      id: `risk-node-${r.id}`,
      title: `Active Risk: ${r.title}`,
      severity: r.data?.priority === "High" ? "high" : "medium",
      confidence: 0.9,
      reason: r.description || "Unresolved risk item.",
      relatedEntities: [{ entityId: r.id, entityType: "node", title: r.title }],
      suggestedActions: ["Create mitigation plan"],
    });
  });
  cycles.forEach((cycle, idx) => {
    risks.push({
      id: `risk-cycle-${idx}`,
      title: `Circular Dependency Loop`,
      severity: "critical",
      confidence: 1.0,
      reason: `Cycle: ${cycle.map((id) => nodeLookup.get(id)?.title || id).join(" -> ")}`,
      relatedEntities: cycle.map((id) => ({
        entityId: id,
        entityType: "node",
        title: nodeLookup.get(id)?.title || id,
      })),
      suggestedActions: ["Sever cycle back-edge"],
    });
  });
  blockedNodes.forEach((bNode) => {
    risks.push({
      id: `risk-blocked-${bNode.id}`,
      title: `Work Blocked: ${bNode.title}`,
      severity: "high",
      confidence: 0.95,
      reason: `"${bNode.title}" is blocked.`,
      relatedEntities: [{ entityId: bNode.id, entityType: "node", title: bNode.title }],
      suggestedActions: ["Investigate blockers", "Assign owner"],
    });
  });

  // Active recommendations from DB
  const activeRecs = await HiveMindRecommendation.find({
    hiveId: new mongoose.Types.ObjectId(hiveId),
    status: "active",
  })
    .lean()
    .exec();

  // Unassigned nodes
  const unassignedNodes = (nodes as WorkspaceNode[]).filter(
    (n) =>
      (n.category === "Feature" || n.category === "Task") &&
      !n.data?.owner &&
      !n.data?.assignee
  );

  // 3. Build candidate plan payloads
  const candidatePlans: Partial<IAgentActionPlan>[] = [];

  // From gaps
  for (const gap of gaps.filter((g) => g.type === "feature_no_prd")) {
    candidatePlans.push(planFromGapFeatureNoPrd(gap, expiryHours));
  }
  for (const gap of gaps.filter((g) => g.type === "arch_no_tech")) {
    candidatePlans.push(planFromGapArchNoTech(gap, expiryHours));
  }

  // From risks — cycles first (highest priority)
  for (const risk of risks.filter((r) => r.id.startsWith("risk-cycle-"))) {
    candidatePlans.push(planFromRiskCycle(risk, expiryHours));
  }
  for (const risk of risks.filter((r) => r.id.startsWith("risk-blocked-"))) {
    candidatePlans.push(planFromRiskBlocked(risk, expiryHours));
  }

  // From unassigned nodes
  for (const node of unassignedNodes.slice(0, 5)) {
    candidatePlans.push(planFromUnassignedNode(node, expiryHours));
  }

  // From active recommendations
  for (const rec of activeRecs) {
    const plan = planFromRecommendation(
      rec as unknown as RecommendationLean,
      expiryHours
    );
    if (Object.keys(plan).length > 0) {
      candidatePlans.push(plan);
    }
  }

  // 4. Filter by confidence threshold
  const qualifiedPlans = candidatePlans
    .filter((p) => p.title && (p.confidence ?? 0) >= confidenceThreshold)
    .slice(0, maxPlansPerRun);

  // 5. Deduplicate — check for existing proposed/approved plans with same title
  const existingTitles = new Set<string>();
  const existing = await AgentActionPlan.find({
    hiveId: new mongoose.Types.ObjectId(hiveId),
    status: { $in: ["proposed", "approved"] },
  })
    .select("title")
    .lean()
    .exec();
  existing.forEach((p) => existingTitles.add(p.title));

  let generated = 0;
  let skipped = 0;
  const createdPlans: IAgentActionPlan[] = [];

  for (const planData of qualifiedPlans) {
    if (!planData.title) { skipped++; continue; }
    if (existingTitles.has(planData.title)) { skipped++; continue; }

    try {
      const plan = await AgentActionPlan.create({
        hiveId: new mongoose.Types.ObjectId(hiveId),
        status: "proposed",
        ...planData,
      });
      createdPlans.push(plan);
      existingTitles.add(planData.title);
      generated++;
    } catch (err) {
      console.error("[ActionEngine] Error creating plan:", err);
      skipped++;
    }
  }

  return { generated, skipped, plans: createdPlans };
}

// ---------------------------------------------------------------------------
// Simulate Action Plan
// ---------------------------------------------------------------------------

/**
 * Simulates the impact of approving an action plan without executing any changes.
 * Returns a rich delta report for display in the UI's impact preview.
 */
export async function simulateActionPlan(
  hiveId: string,
  planId: string
): Promise<ActionSimulationResult | null> {
  const plan = await AgentActionPlan.findOne({
    _id: new mongoose.Types.ObjectId(planId),
    hiveId: new mongoose.Types.ObjectId(hiveId),
  })
    .lean()
    .exec();

  if (!plan) return null;

  // Fetch current workspace state
  const context = await getProjectContext(hiveId);
  const nodes = context.nodes || [];
  const edges = context.edges || [];
  const activeDocs = context.activeDocuments || [];

  // --- Compute current baseline stats ---
  const cycles = detectCycles(nodes, edges);
  const currentCycleCount = cycles.length;

  const docFeatureNodeIds = new Set((activeDocs as WorkspaceDoc[]).map((d) => d.nodeId).filter(Boolean));
  const features = (nodes as WorkspaceNode[]).filter((n) => n.category === "Feature");
  const currentGapCount = features.filter((f) => !docFeatureNodeIds.has(f.id)).length;
  const currentBlockedCount = (nodes as WorkspaceNode[]).filter((n) => n.data?.status === "Blocked").length;

  // --- Simulate step effects ---
  let nodesAdded = 0;
  let nodesModified = 0;
  let nodesDeleted = 0;
  let edgesAdded = 0;
  let edgesDeleted = 0;
  let ownershipChanges = 0;
  let docsAdded = 0;

  for (const step of plan.steps) {
    switch (step.actionType) {
      case "create_node":
        nodesAdded++;
        break;
      case "delete_node":
        nodesDeleted++;
        break;
      case "update_node":
        nodesModified++;
        if (step.params?.updates?.owner !== undefined) ownershipChanges++;
        break;
      case "create_edge":
        edgesAdded++;
        break;
      case "delete_edge":
        edgesDeleted++;
        break;
      case "assign_owner":
        ownershipChanges++;
        nodesModified++;
        break;
      case "create_document":
        docsAdded++;
        nodesAdded++; // Document creates a logical node
        break;
    }
  }

  const dependencyChanges = edgesAdded + edgesDeleted;

  // --- Estimate diagnostic impact ---
  // Risks resolved
  const cycleResolvedByPlan =
    plan.steps.some((s) => s.actionType === "delete_edge") && plan.sourceRiskIds.some((id) => id.startsWith("risk-cycle-"))
      ? Math.min(currentCycleCount, 1)
      : 0;

  const blockedResolvedByPlan =
    plan.steps.some((s) => s.actionType === "assign_owner" || s.actionType === "update_node") &&
    plan.sourceRiskIds.some((id) => id.startsWith("risk-blocked-"))
      ? Math.min(currentBlockedCount, 1)
      : 0;

  const risksResolved = cycleResolvedByPlan + blockedResolvedByPlan;
  const risksCreated = 0; // Plans don't create new risks by design

  // Gaps resolved
  const gapsResolvedByPlan =
    plan.steps.some((s) => s.actionType === "create_document") &&
    plan.sourceGapIds.some((id) => id.startsWith("gap-prd-"))
      ? Math.min(currentGapCount, 1)
      : 0;

  const techGapsResolvedByPlan =
    plan.steps.some((s) => s.actionType === "create_edge") &&
    plan.sourceGapIds.some((id) => id.startsWith("gap-tech-"))
      ? Math.min(currentGapCount - gapsResolvedByPlan, 1)
      : 0;

  const gapsResolved = gapsResolvedByPlan + techGapsResolvedByPlan;
  const gapsCreated = 0;

  // --- Estimate health & momentum delta ---
  // Health formula mirrors hiveMindService.ts scoring
  let estimatedHealthImpact = 0;
  estimatedHealthImpact += risksResolved * 5;          // +5 per risk resolved
  estimatedHealthImpact += gapsResolved * 3;           // +3 per gap closed
  estimatedHealthImpact += ownershipChanges * 2;       // +2 per ownership assigned
  estimatedHealthImpact += cycleResolvedByPlan * 15;   // +15 per cycle fixed (inverse of the -15 penalty)
  estimatedHealthImpact += docsAdded * 3;              // +3 per doc linked (inverse of linked PRDs score)

  // Momentum: ownership changes and activity boosts momentum
  const estimatedMomentumImpact =
    ownershipChanges * 3 + risksResolved * 5 + gapsResolved * 2;

  // --- Affected entity summary ---
  const affectedEntitySet = new Map<string, { entityId: string; entityType: string; title: string; changeType: string }>();
  for (const step of plan.steps) {
    const changeType =
      step.actionType === "delete_node" || step.actionType === "delete_edge"
        ? "removed"
        : step.actionType === "assign_owner" || step.actionType === "update_node"
        ? "modified"
        : "added";

    for (const ent of step.affectedEntities) {
      if (!affectedEntitySet.has(ent.entityId)) {
        affectedEntitySet.set(ent.entityId, { ...ent, changeType });
      }
    }
  }

  const affectedEntities = Array.from(affectedEntitySet.values());

  // --- Reversibility summary ---
  const reversibleSteps = plan.steps.filter((s) => s.reversibility === "reversible").length;
  const irreversibleSteps = plan.steps.length - reversibleSteps;

  const overallRiskLevel: "low" | "medium" | "high" | "critical" = plan.riskLevel;

  return {
    planId,
    nodesAdded,
    nodesModified,
    nodesDeleted,
    risksResolved,
    risksCreated,
    gapsResolved,
    gapsCreated,
    ownershipChanges,
    dependencyChanges,
    estimatedHealthImpact,
    estimatedMomentumImpact,
    affectedEntityCount: affectedEntities.length,
    affectedEntities,
    reversibleSteps,
    irreversibleSteps,
    overallRiskLevel,
  };
}

// ---------------------------------------------------------------------------
// Approve / Reject an Action Plan
// ---------------------------------------------------------------------------

export async function approveActionPlan(
  hiveId: string,
  planId: string,
  actorId: string,
  actorName: string,
  notes?: string
): Promise<IAgentActionPlan | null> {
  const plan = await AgentActionPlan.findOne({
    _id: new mongoose.Types.ObjectId(planId),
    hiveId: new mongoose.Types.ObjectId(hiveId),
    status: "proposed",
  }).exec();

  if (!plan) return null;

  const now = new Date();
  plan.status = "approved";
  plan.approvedBy = new mongoose.Types.ObjectId(actorId);
  plan.approvedAt = now;
  plan.decisionNotes = notes;
  plan.structuredAuditLogs.push({
    actorId: new mongoose.Types.ObjectId(actorId),
    actorName,
    action: "approve",
    notes: notes || "Plan approved.",
    timestamp: now,
  });

  await plan.save();
  return plan;
}

export async function rejectActionPlan(
  hiveId: string,
  planId: string,
  actorId: string,
  actorName: string,
  notes?: string
): Promise<IAgentActionPlan | null> {
  const plan = await AgentActionPlan.findOne({
    _id: new mongoose.Types.ObjectId(planId),
    hiveId: new mongoose.Types.ObjectId(hiveId),
    status: "proposed",
  }).exec();

  if (!plan) return null;

  const now = new Date();
  plan.status = "rejected";
  plan.rejectedBy = new mongoose.Types.ObjectId(actorId);
  plan.rejectedAt = now;
  plan.decisionNotes = notes;
  plan.structuredAuditLogs.push({
    actorId: new mongoose.Types.ObjectId(actorId),
    actorName,
    action: "reject",
    notes: notes || "Plan rejected.",
    timestamp: now,
  });

  await plan.save();
  return plan;
}

// ---------------------------------------------------------------------------
// Expire Stale Plans (for cron / background runs)
// ---------------------------------------------------------------------------

/**
 * Marks all proposed plans that have passed their expiresAt date as expired.
 * Should be called at the start of each generateActionPlans run and/or via a cron job.
 */
export async function expireStalePlans(hiveId?: string): Promise<number> {
  const now = new Date();
  const filter: Record<string, unknown> = {
    status: "proposed",
    expiresAt: { $lt: now },
  };
  if (hiveId) {
    (filter as Record<string, unknown>).hiveId = new mongoose.Types.ObjectId(hiveId);
  }

  const plans = await AgentActionPlan.find(filter).exec();

  let expiredCount = 0;
  for (const plan of plans) {
    plan.status = "expired";
    plan.structuredAuditLogs.push({
      actorId: undefined,
      actorName: "HiveMind Expiry Engine",
      action: "expire",
      notes: `Plan automatically expired at ${now.toISOString()} (was due ${plan.expiresAt.toISOString()}).`,
      timestamp: now,
    });
    await plan.save();
    expiredCount++;
  }

  return expiredCount;
}
